#!/usr/bin/env python3
#
# Copyright (c) 2026 Mateusz Żerebecki
#
# SPDX-License-Identifier: Apache-2.0
#
# Turn recorded wheel_cal.py captures into a C header the replay test can use.
#
# A capture is a CSV file with '#' metadata lines (odr_hz, range_g, ...) followed
# by a 't_us,ax_mg,ay_mg,az_mg' table - the format app/tools/wheel_cal.py writes.
# Embedding the samples as arrays keeps the test hermetic: no filesystem, no
# working directory to get wrong on the way to the runner.
#
# Usage:
#   csv_to_header.py OUTPUT.h fixtures/*.csv
#
# Timestamps are rebased to the first sample, so a capture can be replayed on
# its own. The array name comes from the file stem, which means adding a capture
# is just dropping the CSV into fixtures/.

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# The captures store milli-g; the detector takes m/s^2.
MG_TO_MS2 = 9.80665e-3

ROW_HEADER = "t_us"
IDENT = re.compile(r"[^0-9a-zA-Z_]")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path, help="header file to write")
    parser.add_argument("captures", type=Path, nargs="+", help="capture CSVs")
    return parser.parse_args()


def identifier(stem: str) -> str:
    name = IDENT.sub("_", stem)
    if name[0].isdigit():
        name = f"fx_{name}"
    return name


def parse_capture(path: Path) -> tuple[dict[str, str], list[tuple[int, int, int, int]]]:
    meta: dict[str, str] = {}
    rows: list[tuple[int, int, int, int]] = []

    with path.open(encoding="utf-8") as handle:
        for lineno, raw in enumerate(handle, 1):
            line = raw.strip()
            if not line:
                continue
            if line.startswith("#"):
                key, sep, value = line[1:].partition("=")
                if sep:
                    meta[key.strip()] = value.strip()
                continue
            if line.startswith(ROW_HEADER):
                continue

            parts = line.split(",")
            if len(parts) != 4:
                raise SystemExit(f"{path}:{lineno}: expected 4 columns, got {len(parts)}")
            try:
                t_us, ax, ay, az = (int(part) for part in parts)
            except ValueError:
                raise SystemExit(f"{path}:{lineno}: non-integer sample") from None
            rows.append((t_us, ax, ay, az))

    if not rows:
        raise SystemExit(f"{path}: no samples")

    return meta, rows


def emit(out: list[str], path: Path) -> str:
    stem = path.stem
    name = identifier(stem)
    meta, rows = parse_capture(path)

    for key in ("odr_hz", "range_g"):
        if key not in meta:
            raise SystemExit(f"{path}: missing '{key}' in the capture header")

    t0 = rows[0][0]
    out.append(f"/* {path.name}: {meta.get('captured', 'unknown')} */")
    out.append(f"static const struct fixture_sample {name}_samples[] = {{")
    for t_us, ax, ay, az in rows:
        out.append(
            f"\t{{ {(t_us - t0) / 1e6:.6f}f, {ax * MG_TO_MS2:.6f}f, "
            f"{ay * MG_TO_MS2:.6f}f, {az * MG_TO_MS2:.6f}f }},")
    out.append("};")
    out.append("")
    return (
        f'\t{{ "{stem}", {meta["odr_hz"]}, {meta["range_g"]}, '
        f"ARRAY_SIZE({name}_samples), {name}_samples }},"
    )


def main() -> int:
    args = parse_args()

    body: list[str] = []
    entries: list[str] = []
    for capture in sorted(args.captures):
        entries.append(emit(body, capture))

    lines = [
        "/*",
        " * Generated by tools/csv_to_header.py - do not edit.",
        " *",
        " * Samples come from captured wheel motion (see fixtures/README.md).",
        " */",
        "#ifndef WHEEL_DETECTOR_FIXTURES_H_",
        "#define WHEEL_DETECTOR_FIXTURES_H_",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "#include <zephyr/sys/util.h>",
        "",
        "struct fixture_sample {",
        "\tfloat t_s;",
        "\tfloat x_ms2;",
        "\tfloat y_ms2;",
        "\tfloat z_ms2;",
        "};",
        "",
        "struct fixture {",
        "\tconst char *name;",
        "\tuint32_t odr_hz;",
        "\tuint32_t range_g;",
        "\tsize_t count;",
        "\tconst struct fixture_sample *samples;",
        "};",
        "",
    ]
    lines += body
    lines += [
        "static const struct fixture fixtures[] = {",
        *entries,
        "};",
        "#define FIXTURE_COUNT ARRAY_SIZE(fixtures)",
        "",
        "#endif /* WHEEL_DETECTOR_FIXTURES_H_ */",
        "",
    ]

    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.output} ({len(entries)} fixtures)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
